# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random Walk using Rcpp
#' @description A Random Walk sampler using Rcpp
#' @param sigma the standard deviation of the normal random increment with a zero mean 
#' @param x0 the initial iteration point
#' @param N the designated number of random numbers (including the initial point x0)
#' @return the sample
#' @examples
#' \dontrun{
#' laplace<-function(x) return(1/2*exp(-abs(x)))
#' lC <- randomwalkC(1,25,1000);
#' }
#' @export
randomwalkC <- function(sigma, x0, N) {
    .Call('_SC19013_randomwalkC', PACKAGE = 'SC19013', sigma, x0, N)
}

